spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/productdelivery
    username: postgres
    password: Mklauro@2024

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    url: ${DB_URL_POSTGRESQL}
    user: ${DB_USERNAME_POSTGRESQL}
    password: ${DB_PASSWORD_POSTGRESQL}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false


google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}